faiss_db:
  collection_name: "StockSnapAI"

chroma_db:
  CHROMA_PERSIST_DIRECTORY: "./vdb_data/chroma_db"
  CHUNK_SIZE: 1000
  CHUNK_OVERLAP: 200
  RETRIEVAL_K: 4

 # File Configuration
UPLOAD_DIR: "./uploads"
MAX_FILE_SIZE:  50 * 1024 * 1024  # 50MB
ALLOWED_EXTENSIONS:  [".pdf", ".txt", ".docx", ".xlsx", ".csv"]

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-small"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0.2
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0.2
    max_output_tokens: 2048

  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0.2
    max_output_tokens: 2048
